import type { Loc } from "./locale";

export type Edibility = "choice" | "edible" | "caution" | "toxic" | "deadly";
export type Shape =
  | "bolete" | "amanita" | "chanterelle" | "morel"
  | "oyster" | "parasol" | "puffball" | "trumpet" | "coral";

export interface Species {
  n: string;        // nombre científico (no se traduce)
  com: Loc;         // nombre común
  edib: Edibility;
  shape: Shape;
  cap: string; cap2?: string; stem?: string; dots?: boolean;
  hab: Loc; season: Loc; note: Loc; twin: Loc; region: Loc;
}

export interface FieldGuide {
  harvest: Loc; dry: Loc; touch: Loc; where: Loc; clusters: Loc; hours: Loc; aspect: Loc;
}

export const SPECIES_TOTAL = 128;

const L = (en: string, es: string): Loc => ({ en, es });

// Catálogo ilustrado (24 de 128+). Bilingüe EN/ES.
export const SPECIES: Species[] = [
  { n: "Boletus edulis", com: L("Porcini / King bolete", "Porcini / Boleto"), edib: "choice", shape: "bolete", cap: "#8a4b2a", cap2: "#6d3a20", hab: L("Beech & oak woods", "Hayedos, robledales"), season: L("Autumn", "Otoño"), note: L("White flesh that doesn't change when cut. The king of edibles.", "Carne blanca que no vira al corte. El rey de los comestibles."), twin: L("Tylopilus felleus (bitter)", "Tylopilus felleus (amargo)"), region: L("Europe, North America", "Europa, Norteamérica") },
  { n: "Boletus aereus", com: L("Bronze bolete", "Boleto negro"), edib: "choice", shape: "bolete", cap: "#4a3526", cap2: "#33241a", hab: L("Oak & cork-oak woods", "Encinares, alcornocales"), season: L("Autumn", "Otoño"), note: L("Very dark brown cap, better than edulis for many.", "Sombrero pardo muy oscuro, superior al edulis para muchos."), twin: L("Tylopilus felleus", "Tylopilus felleus"), region: L("Mediterranean", "Mediterráneo") },
  { n: "Boletus pinophilus", com: L("Pine bolete", "Boleto de pino"), edib: "choice", shape: "bolete", cap: "#7a3b22", cap2: "#5a2c18", hab: L("Pine woods", "Pinares"), season: L("Autumn", "Otoño"), note: L("Reddish tones, associated with conifers.", "Tonos rojizos, asociado a coníferas."), twin: L("Tylopilus felleus", "Tylopilus felleus"), region: L("Europe", "Europa") },
  { n: "Cantharellus cibarius", com: L("Chanterelle", "Rebozuelo"), edib: "choice", shape: "chanterelle", cap: "#d29a3e", cap2: "#b07d28", hab: L("Conifers & broadleaves", "Coníferas y caducifolios"), season: L("Summer-Autumn", "Verano-Otoño"), note: L("Egg-yellow, fruity smell, false gills.", "Amarillo yema, olor afrutado, falsos pliegues."), twin: L("Hygrophoropsis aurantiaca", "Hygrophoropsis aurantiaca"), region: L("Europe", "Europa") },
  { n: "Craterellus cornucopioides", com: L("Horn of plenty", "Trompeta de los muertos"), edib: "edible", shape: "trumpet", cap: "#3a322b", cap2: "#2e231b", hab: L("Beech & oak woods", "Hayedos, robledales"), season: L("Autumn", "Otoño"), note: L("Black and hollow, excellent dried.", "Negra y hueca, excelente seca."), twin: L("No dangerous look-alikes", "Sin sosias peligrosos"), region: L("France, Italy", "Francia, Italia") },
  { n: "Lactarius deliciosus", com: L("Saffron milk cap", "Níscalo / Rovellón"), edib: "choice", shape: "bolete", cap: "#c97a3c", cap2: "#a65f28", hab: L("Pine woods", "Pinares"), season: L("Autumn", "Otoño"), note: L("Orange latex, turns green (normal).", "Látex anaranjado, vira a verde (normal)."), twin: L("Lactarius torminosus", "Lactarius torminosus"), region: L("Spain, southern Europe", "España, sur de Europa") },
  { n: "Amanita caesarea", com: L("Caesar's mushroom", "Oronja"), edib: "choice", shape: "amanita", cap: "#e0741f", cap2: "#b85a14", stem: "#f2d96b", dots: false, hab: L("Oak & chestnut woods", "Encinares, castañares"), season: L("Summer-Autumn", "Verano-Otoño"), note: L("Orange, yellow gills and stem, white volva.", "Naranja, láminas y pie amarillos, volva blanca."), twin: L("Amanita muscaria", "Amanita muscaria"), region: L("Italy, Spain", "Italia, España") },
  { n: "Morchella esculenta", com: L("Morel", "Colmenilla"), edib: "choice", shape: "morel", cap: "#a8895c", cap2: "#7d6440", hab: L("Riverbanks, ash woods", "Riberas, fresnedas"), season: L("Spring", "Primavera"), note: L("Honeycombed, hollow head. Toxic raw, edible cooked.", "Cabeza alveolada, hueca. Tóxica cruda, comestible cocinada."), twin: L("Gyromitra (false morel)", "Gyromitra (falsa colmenilla)"), region: L("Europe, North America", "Europa, Norteamérica") },
  { n: "Calocybe gambosa", com: L("St. George's mushroom", "Seta de San Jorge"), edib: "choice", shape: "bolete", cap: "#e6dcc4", cap2: "#cbbf9e", hab: L("Meadows, hedgerows", "Prados, setos"), season: L("Spring", "Primavera"), note: L("Fleshy, white, smell of fresh flour.", "Carnosa, blanca, olor a harina fresca."), twin: L("Entoloma lividum", "Entoloma lividum"), region: L("Northern Spain", "Norte de España") },
  { n: "Pleurotus ostreatus", com: L("Oyster mushroom", "Seta de ostra"), edib: "edible", shape: "oyster", cap: "#c9c0ad", cap2: "#9c9283", hab: L("Deciduous trunks", "Troncos caducos"), season: L("Autumn-Winter", "Otoño-Invierno"), note: L("Grows in shelves, decurrent gills.", "Crece en repisas, láminas decurrentes."), twin: L("Omphalotus (bioluminescent)", "Omphalotus (bioluminiscente)"), region: L("Worldwide", "Mundial") },
  { n: "Macrolepiota procera", com: L("Parasol mushroom", "Parasol"), edib: "edible", shape: "parasol", cap: "#b09372", cap2: "#7d6448", hab: L("Meadows, clearings", "Prados, claros"), season: L("Autumn", "Otoño"), note: L("Scales, double sliding ring. Cap only.", "Escamas, anillo doble móvil. Solo el sombrero."), twin: L("Chlorophyllum", "Chlorophyllum"), region: L("Europe", "Europa") },
  { n: "Hydnum repandum", com: L("Hedgehog mushroom", "Lengua de gato"), edib: "edible", shape: "bolete", cap: "#d9b87e", cap2: "#bd9a5e", hab: L("Mixed woods", "Bosques mixtos"), season: L("Autumn", "Otoño"), note: L("Spines instead of gills. Unmistakable.", "Aguijones en vez de láminas. Inconfundible."), twin: L("No dangerous look-alikes", "Sin sosias peligrosos"), region: L("Europe", "Europa") },
  { n: "Agaricus campestris", com: L("Field mushroom", "Champiñón silvestre"), edib: "edible", shape: "bolete", cap: "#e8ddd0", cap2: "#c9b79c", hab: L("Meadows, pastures", "Prados, pastos"), season: L("Autumn", "Otoño"), note: L("Pink to chocolate-brown gills.", "Láminas rosas a marrón chocolate."), twin: L("Amanita (DEADLY)", "Amanita (MORTAL)"), region: L("Worldwide", "Mundial") },
  { n: "Ramaria botrytis", com: L("Rosso coral", "Manita / Coral"), edib: "edible", shape: "coral", cap: "#d9a679", cap2: "#b8855a", stem: "#e8dccd", hab: L("Mixed woods", "Bosques mixtos"), season: L("Autumn", "Otoño"), note: L("Coral-shaped, pinkish tips.", "Forma de coral, puntas rosadas."), twin: L("Ramaria formosa (laxative)", "Ramaria formosa (laxante)"), region: L("Europe", "Europa") },
  { n: "Cantharellus tubaeformis", com: L("Yellowfoot", "Trompeta amarilla"), edib: "edible", shape: "chanterelle", cap: "#c89a4e", cap2: "#a07a30", hab: L("Mossy conifers", "Coníferas musgosas"), season: L("Late autumn", "Otoño tardío"), note: L("Hollow yellow stem, grows in groups.", "Pie hueco amarillo, crece en grupos."), twin: L("No dangerous look-alikes", "Sin sosias peligrosos"), region: L("Europe", "Europa") },
  { n: "Lactarius sanguifluus", com: L("Bloody milk cap", "Níscalo de sangre"), edib: "choice", shape: "bolete", cap: "#b85a4a", cap2: "#963f30", hab: L("Limestone pine woods", "Pinares calizos"), season: L("Autumn", "Otoño"), note: L("Wine-red latex. Highly prized.", "Látex rojo vino. Muy apreciado."), twin: L("Other Lactarius", "Otros Lactarius"), region: L("Mediterranean", "Mediterráneo") },
  { n: "Tuber melanosporum", com: L("Black truffle", "Trufa negra"), edib: "choice", shape: "puffball", cap: "#2e231b", cap2: "#1a1410", hab: L("Oak woods (underground)", "Encinares (subterránea)"), season: L("Winter", "Invierno"), note: L("Hypogeous, intense aroma. Found with a dog.", "Hipogea, aroma intenso. Se busca con perro."), twin: L("Aroma-less truffles", "Trufas sin aroma"), region: L("France, Spain, Italy", "Francia, España, Italia") },
  { n: "Agaricus bisporus", com: L("Button mushroom", "Champiñón común"), edib: "edible", shape: "bolete", cap: "#e0d2c0", cap2: "#c2b09a", hab: L("Cultivated / meadows", "Cultivado / prados"), season: L("All year", "Todo el año"), note: L("The market mushroom, also wild.", "El champiñón de mercado, también silvestre."), twin: L("White Amanita", "Amanita blanca"), region: L("Worldwide", "Mundial") },
  { n: "Amanita muscaria", com: L("Fly agaric", "Matamoscas"), edib: "toxic", shape: "amanita", cap: "#c8341f", cap2: "#a02816", hab: L("Birches, pines", "Abedules, pinos"), season: L("Autumn", "Otoño"), note: L("Red with white flecks. Psychoactive and toxic.", "Roja con motas blancas. Psicoactiva y tóxica."), twin: L("A. caesarea (edible)", "A. caesarea (comestible)"), region: L("Worldwide", "Mundial") },
  { n: "Amanita pantherina", com: L("Panther cap", "Amanita pantera"), edib: "toxic", shape: "amanita", cap: "#9a7048", cap2: "#7a5636", hab: L("Mixed woods", "Bosques mixtos"), season: L("Autumn", "Otoño"), note: L("Brown with white flecks. Neurotoxic.", "Parda con motas blancas. Neurotóxica."), twin: L("Amanita rubescens", "Amanita rubescens"), region: L("Europe", "Europa") },
  { n: "Amanita phalloides", com: L("Death cap", "Oronja verde"), edib: "deadly", shape: "amanita", cap: "#9aa86b", cap2: "#7a8a4e", dots: false, hab: L("Oak & beech woods", "Robledales, hayedos"), season: L("Autumn", "Otoño"), note: L("Causes most deaths. Greenish cap, volva.", "Causa la mayoría de muertes. Sombrero verdoso, volva."), twin: L("Edible Agaricus, Amanita", "Agaricus, Amanita comestibles"), region: L("Worldwide", "Mundial") },
  { n: "Galerina marginata", com: L("Deadly galerina", "Galerina mortal"), edib: "deadly", shape: "bolete", cap: "#a06b3a", cap2: "#7d5028", hab: L("Dead wood", "Madera muerta"), season: L("Autumn", "Otoño"), note: L("Small, brown. Same toxins as the death cap.", "Pequeña, marrón. Mismas toxinas que la phalloides."), twin: L("Edible stump mushrooms", "Setas de tocón comestibles"), region: L("Worldwide", "Mundial") },
  { n: "Cortinarius rubellus", com: L("Deadly webcap", "Cortinario mortal"), edib: "deadly", shape: "bolete", cap: "#9a4a26", cap2: "#7a3618", hab: L("Damp conifers", "Coníferas húmedas"), season: L("Autumn", "Otoño"), note: L("Delayed kidney damage (days later).", "Daño renal tardío (días después)."), twin: L("Chanterelles by color", "Rebozuelos por color"), region: L("Europe", "Europa") },
  { n: "Gyromitra esculenta", com: L("False morel", "Falsa colmenilla"), edib: "deadly", shape: "morel", cap: "#7a3a20", cap2: "#5a2414", hab: L("Sandy pine woods", "Pinares arenosos"), season: L("Spring", "Primavera"), note: L("Brain-like, not honeycombed. Lethally toxic.", "Cerebriforme, no alveolada. Tóxica letal."), twin: L("True morel", "Colmenilla verdadera"), region: L("Europe, North America", "Europa, Norteamérica") },
];

// Guía de campo por especie (bilingüe).
export const FIELD_GUIDE: Record<string, FieldGuide> = {
  "Boletus edulis": { harvest: L("Cut or gently twist from the base; don't dig up the mycelium.", "Corta o gira suavemente desde la base; no escarbes el micelio."), dry: L("Excellent for drying: thin slices, dehydrate at 40°C.", "Excelente para secar: láminas finas, deshidratar a 40°C."), touch: L("Safe to touch.", "Se puede tocar sin riesgo."), where: L("On the ground, under beech, oak and chestnut (mycorrhiza).", "En el suelo, bajo hayas, robles y castaños (micorriza)."), clusters: L("If you find one, look around: there are usually more within a few meters.", "Si encuentras uno, busca alrededor: suele haber más en un radio de pocos metros."), hours: L("Best early morning, after humid nights.", "Mejor a primera hora de la mañana, tras noches húmedas."), aspect: L("On the ground, never buried. Look for the cap among the leaf litter.", "Sobre el suelo, nunca enterrado. Busca el sombrero entre la hojarasca.") },
  "Cantharellus cibarius": { harvest: L("Cut with a knife at ground level so as not to damage the mycelium.", "Corta con navaja a ras de suelo para no dañar el micelio."), dry: L("Better preserved or frozen; drying loses aroma.", "Mejor en conserva o congelado; al secar pierde aroma."), touch: L("Safe to touch.", "Sin riesgo al tacto."), where: L("Forest floor of conifers and broadleaves, among moss.", "Suelo de bosques de coníferas y caducifolios, entre musgo."), clusters: L("Grows in groups: if you see one, there's almost always a colony.", "Crece en grupos: si ves uno, casi siempre hay una colonia."), hours: L("Any time; more visible with morning side-light.", "Cualquier hora; más visibles con luz lateral de la mañana."), aspect: L("On the ground, sometimes half-hidden among moss and leaves.", "Sobre el suelo, a veces semi-oculto entre musgo y hojas.") },
  "Lactarius deliciosus": { harvest: L("Twist and pull carefully; check the stem for worms.", "Gira y tira con cuidado; revisa que no tenga gusanos en el pie."), dry: L("Not ideal for drying; better in oil or grilled.", "No ideal para secar; mejor en aceite o a la brasa."), touch: L("Safe; stains fingers orange (normal).", "Sin riesgo; mancha los dedos de naranja (normal)."), where: L("Pine forest floor, often in grassy patches under pines.", "Suelo de pinares, a menudo en zonas de pasto bajo pinos."), clusters: L("Appears in scattered groups; sweep the pine area.", "Aparece en grupos dispersos; rastrea la zona del pinar."), hours: L("Morning, after autumn rains.", "Mañana, tras lluvias de otoño."), aspect: L("On the ground, the cap sometimes barely peeks out.", "Sobre el suelo, el sombrero a veces apenas asoma.") },
  "Tuber melanosporum": { harvest: L("Extracted with a trained dog and tool; it's underground.", "Se extrae con perro adiestrado y herramienta; es subterránea."), dry: L("Not dried; used fresh or kept cold.", "No se seca; se usa fresca o conservada en frío."), touch: L("Safe.", "Sin riesgo."), where: L("BURIED, by the roots of holm oak and oak (5-30 cm).", "ENTERRADA, junto a raíces de encina y roble (5-30 cm)."), clusters: L("Truffle grounds produce several in the same area year after year.", "Las truferas producen varias en la misma zona año tras año."), hours: L("Winter season; the search is by the dog's smell.", "Temporada invernal; la búsqueda es por olfato del perro."), aspect: L("Underground: impossible to see on the surface, only smelled.", "Bajo tierra: imposible verla en superficie, solo se huele.") },
  "Morchella esculenta": { harvest: L("Cut at ground level; hollow inside (sign of authenticity).", "Corta a ras de suelo; hueca por dentro (señal de autenticidad)."), dry: L("Excellent dried; intensifies the flavor.", "Excelente seca; intensifica el sabor."), touch: L("Safe, but ALWAYS cook (toxic raw).", "Sin riesgo, pero SIEMPRE cocinar (tóxica cruda)."), where: L("Riverbanks, ash woods, areas burned the previous year.", "Suelo de riberas, fresnedas, zonas quemadas el año anterior."), clusters: L("Usually comes out in groups; check the surroundings well.", "Suele salir en grupos; revisa bien el entorno."), hours: L("Spring, after mild and humid days.", "Primavera, tras días templados y húmedos."), aspect: L("On the ground, camouflaged: its color blends with leaf litter.", "Sobre el suelo, camuflada: su color se confunde con hojarasca.") },
};
